all:

install:
	install -d shiny-app-ex ../bin/shiny-app-ex
	install --mode 0444 -t ../bin/shiny-app-ex shiny-app-ex/*

clean:

distclean: clean
	rm -f ../bin/shiny-app-ex

.PHONY: all install clean distclean
